authorName: Yotta
experimentName: T-LSTM
trialConcurrency: 2
maxExecDuration: 24h
maxTrialNum: 30
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
assessor:
  #choice: Medianstop, Curvefitting
  builtinAssessorName: Curvefitting
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
    epoch_num: 32
    start_step: 10
trial:
  command: python3 BERT_THREE_PARSER.py
  codeDir: .
  gpuNum: 1
